{ Copyright (C) 1981 by Bell Laboratories, Inc., and Whitesmiths Ltd. }
{ macproc -- procedures for macro }
#include "cscopy.p"
#include "sccopy.p"
#include "putback.p"
#include "getpbc.p"
#include "pbstr.p"
#include "pbnum.p"
#include "gettok.p"
#include "inithash.p"
#include "hash.p"
#include "hashfind.p"
#include "install.p"
#include "lookup.p"
#include "push.p"
#include "putchr.p"
#include "puttok.p"
#include "expr.p"
#include "dodef.p"
#include "doif.p"
#include "doexpr.p"
#include "dolen.p"
#include "dochq.p"
#include "dosub.p"
#include "eval.p"
#include "initmacro.p"
